constant_tags = {'TAG_CONSTANT_DEFAULT': -1,\
    'TAG_CONSTANT_CLASS': 7,\
    'TAG_CONSTANT_FIELDREF': 9,\
    'TAG_CONSTANT_METHODREF': 10,\
    'TAG_CONSTANT_INTERFACE_METHODREF': 11,\
    'TAG_CONSTANT_STRING': 8,\
    'TAG_CONSTANT_INTEGER': 3,\
    'TAG_CONSTANT_FLOAT': 4,\
    'TAG_CONSTANT_LONG': 5,\
    'TAG_CONSTANT_DOUBLE': 6,\
    'TAG_CONSTANT_NAME_AND_TYPE': 12,\
    'TAG_CONSTANT_UTF8': 1,\
    'TAG_CONSTANT_METHOD_HANDLE': 15,\
    'TAG_CONSTANT_METHOD_TYPE': 16,\
    'TAG_CONSTANT_INVOKE_DYNAMIC': 18,\
    'TAG_CONSTANT_MODULE': 19,\
    'TAG_CONSTANT_PACKAGE': 20
    }
